#!/usr/bin/env node

/**
 * Extracts icons from the `lucide` package and compiles them into
 * a single `webview/src/icons.js` file exposing a flat map of:
 * { "icon-name": "M ... path d ..." }
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { icons } from 'lucide';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'webview', 'src', 'icons.js');

function toPath(tag, attrs) {
  if (tag === 'path') return attrs.d;
  if (tag === 'circle') {
    const cx = +attrs.cx, cy = +attrs.cy, r = +attrs.r;
    return `M ${cx - r},${cy} a ${r},${r} 0 1,0 ${r * 2},0 a ${r},${r} 0 1,0 ${-r * 2},0`;
  }
  if (tag === 'line') {
    return `M ${attrs.x1},${attrs.y1} L ${attrs.x2},${attrs.y2}`;
  }
  if (tag === 'rect') {
    const x = +attrs.x, y = +attrs.y, w = +attrs.width, h = +attrs.height, rx = +(attrs.rx || 0);
    if (!rx) return `M ${x},${y} h ${w} v ${h} h ${-w} Z`;
    return `M ${x + rx},${y} h ${w - 2 * rx} a ${rx},${rx} 0 0,1 ${rx},${rx} v ${h - 2 * rx} a ${rx},${rx} 0 0,1 ${-rx},${rx} h ${-(w - 2 * rx)} a ${rx},${rx} 0 0,1 ${-rx},${-rx} v ${-(h - 2 * rx)} a ${rx},${rx} 0 0,1 ${rx},${-rx} Z`;
  }
  if (tag === 'ellipse') {
    const cx = +attrs.cx, cy = +attrs.cy, rx = +attrs.rx, ry = +attrs.ry;
    return `M ${cx - rx},${cy} a ${rx},${ry} 0 1,0 ${rx * 2},0 a ${rx},${ry} 0 1,0 ${-rx * 2},0`;
  }
  if (tag === 'polygon' || tag === 'polyline') {
    const pts = attrs.points.trim().split(/[\\s,]+/).reduce((acc, curr, i, arr) => {
      if (i % 2 === 0) acc.push(`${curr},${arr[i + 1]}`);
      return acc;
    }, []);
    return `M ${pts.join(' L ')}${tag === 'polygon' ? ' Z' : ''}`;
  }
  return '';
}

const result = {};

for (const [name, elements] of Object.entries(icons)) {
  // elements is e.g. [ ["path", {d: "..."}], ["circle", {...}] ]
  const dPaths = elements.map(el => toPath(el[0], el[1])).filter(Boolean);
  // Convert icon name format from PascalCase (AArrowDown) to kebab-case (a-arrow-down)
  const kebabName = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  result[kebabName] = dPaths.join(' ');
}

const content = `// ─── icons.js ─── Auto-extracted from icons.js
// This file is part of the FD webview module system.
// Build with: pnpm run build:webview
// 
// AUTO-GENERATED by scripts/build-icons.mjs - Do not edit directly
window.lucideIcons = ${JSON.stringify(result)};
`;

writeFileSync(outPath, content);
console.log(`Successfully compiled ${Object.keys(result).length} Lucide icons to webview/src/icons.js`);
